---
- hosts: localhost
  become: yes
  tasks:
   - name: install apache
     package:
      name: apache2
      state: latest
     when:
      ansible_os_family == "Debian"
   - name: install httpd
     package:
      name: httpd
     when:
      ansible_os_family == "RedHat"
